/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kryptnostic_krypto_engine_KryptnosticEngine */

#ifndef _Included_com_kryptnostic_krypto_engine_KryptnosticEngine
#define _Included_com_kryptnostic_krypto_engine_KryptnosticEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kryptnostic_krypto_engine_KryptnosticEngine
 * Method:    initKryptnosticEngine
 * Signature: ([B[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_kryptnostic_krypto_engine_KryptnosticEngine_initKryptnosticEngine
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_kryptnostic_krypto_engine_KryptnosticEngine
 * Method:    getAddress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kryptnostic_krypto_engine_KryptnosticEngine_getAddress
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
